name: zem_taxi
description: Zém & Taxi - Votre transport au Togo
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.2
  pin_code_fields: ^8.0.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
